# Generated by Django 3.0.1 on 2020-02-18 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200218_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 18, 11, 40, 12, 856739, tzinfo=utc)),
        ),
    ]
